export {
  STATUS_CAMPANHA_LABEL,
  STATUS_CAMPANHA_VARIANT,
  TIPO_MECANICA_LABEL,
  CRITERIO_PDV_NOVO_LABEL,
  UNIDADE_VOLUME_LABEL,
  MODO_PREMIACAO_LABEL,
  TIPO_PREMIO_LABEL,
  TIPO_BENEFICIARIO_LABEL,
} from "../types";
